In [284]:
%load_ext autoreload
%autoreload 2
import numpy as np
from seal_wrapper import EA

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [285]:
# model
w = [0.1, 0.05, 0.05, 0.2, 0.05, 0.3, 0.1, 0.025, 0.075, 0.05]
# data (sensitive)
x = [3.1, 4.159, 2.65, 3.5897, 9.3, 2.3, 8.46, 2.64, 3.383, 2.795]

In [286]:
np.sum(np.array(w)*np.array(x))

3.828865

In [287]:
np.dot(w, x)

3.828865

In [314]:
encoded_w = EA(np.array(w))
encrypted_x = EA(np.array(x), True)

In [315]:
encrypted_x.vector_mul(encoded_w)

In [317]:
x_dot_w = encrypted_x.vector_mul(encoded_w)
x_dot_w.values()

3.8288649999999986

In [291]:
print(w)
print(encoded_w.values())

[0.1, 0.05, 0.05, 0.2, 0.05, 0.3, 0.1, 0.025, 0.075, 0.05]
[0.1   0.05  0.05  0.2   0.05  0.3   0.1   0.025 0.075 0.05 ]


In [292]:
print(x)
print(encrypted_x.values())

[3.1, 4.159, 2.65, 3.5897, 9.3, 2.3, 8.46, 2.64, 3.383, 2.795]
[3.1    4.159  2.65   3.5897 9.3    2.3    8.46   2.64   3.383  2.795 ]


In [293]:
w2 = [[1, 2, 3], [4, 5, 6]]
encoded_w2 = EA(np.array(w2).T)

In [294]:
encoded_w2.values()

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [295]:
x2 = [[1, 2, 3], [4, 5, 6]]
encrypted_x2 = EA(np.array(x2), True)

In [296]:
encrypted_x2.values()

array([[1., 2., 3.],
       [4., 5., 6.]])

In [297]:
dot_product = encrypted_x2 @ encoded_w2

In [299]:
dot_product.values()

array([[14., 32.],
       [32., 77.]])