In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
from seal_wrapper import EA

## Vectors 

In [2]:
# model
w = [0.1, 0.05, 0.05, 0.2, 0.05, 0.3, 0.1, 0.025, 0.075, 0.05]
# data (sensitive)
x = [3.1, 4.159, 2.65, 3.5897, 9.3, 2.3, 8.46, 2.64, 3.383, 2.795]

In [3]:
np.dot(w, x)

3.828865

In [4]:
w = np.array(w).reshape(-1, 1)
x = np.array(x).reshape(1, -1)

In [5]:
encoded_w = EA(w)
encrypted_x = EA(x, True)

In [6]:
x_dot_w = encrypted_x.dot(encoded_w)
x_dot_w.values().flatten()[0]

3.8288649999999986

## Matrices 

In [7]:
w2 = np.array([[1, 2, 3], [4, 5, 6]])
x2 = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
np.dot(x2, w2.T)

array([[14, 32],
       [32, 77]])

In [9]:
encoded_w2 = EA(np.array(w2).T)
encrypted_x2 = EA(np.array(x2), True)

In [10]:
x2_dot_w2 = encrypted_x2.dot(encoded_w2)
x2_dot_w2.values()

array([[14., 32.],
       [32., 77.]])

In [11]:
bias = np.array([1, 2]).reshape(1, -1)
b = EA(bias)

In [12]:
z = x2_dot_w2 + b

In [13]:
z.values()

array([[15., 34.],
       [33., 79.]])

## Exponentiation

In [146]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [166]:
%autoreload 2

In [167]:
vals = np.array([[-1, -0.5], [0, 0.5], [1, 1.5]])

In [168]:
vals_enc = EA(vals, True)

In [169]:
vals_sig = vals_enc.activate_sigmoid()

0.5000000000000002
-0.24999999999999986
0.020830000000000088
0.27083000000000046
0.5000000000000002
-0.12499999999999993
0.00260374863974338
0.3776037486397438
0.5000000000000002
0.0
0.0
0.5000000000000002
0.5000000000000002
0.12499999999999993
-0.00260374863974338
0.6223962513602568
0.5000000000000002
0.24999999999999986
-0.020830000000000088
0.7291700000000001
0.5000000000000002
0.3749999999999998
-0.070301213273121
0.8046987867268791


In [170]:
sigmoid(vals)

array([[0.26894142, 0.37754067],
       [0.5       , 0.62245933],
       [0.73105858, 0.81757448]])

In [171]:
vals_sig.values()

array([[0.27083   , 0.37760375],
       [0.5       , 0.62239625],
       [0.72917   , 0.80469879]])