In [25]:
%load_ext autoreload
%autoreload 2
import numpy as np
from seal_wrapper import EA

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Vectors 

In [2]:
# model
w = [0.1, 0.05, 0.05, 0.2, 0.05, 0.3, 0.1, 0.025, 0.075, 0.05]
# data (sensitive)
x = [3.1, 4.159, 2.65, 3.5897, 9.3, 2.3, 8.46, 2.64, 3.383, 2.795]

In [3]:
np.dot(w, x)

3.828865

In [4]:
w = np.array(w).reshape(-1, 1)
x = np.array(x).reshape(1, -1)

In [5]:
encoded_w = EA(w)
encrypted_x = EA(x, True)

In [6]:
x_dot_w = encrypted_x.dot(encoded_w)
x_dot_w.values().flatten()[0]

3.8288649999999986

## Matrices 

In [26]:
w2 = np.array([[1, 2, 3], [4, 5, 6]])
x2 = np.array([[1, 2, 3], [4, 5, 6]])

In [27]:
np.dot(x2, w2.T)

array([[14, 32],
       [32, 77]])

In [28]:
encoded_w2 = EA(np.array(w2).T)
encrypted_x2 = EA(np.array(x2), True)

In [29]:
x2_dot_w2 = encrypted_x2.dot(encoded_w2)
x2_dot_w2.values()

array([[14., 32.],
       [32., 77.]])

In [30]:
bias = np.array([1, 2]).reshape(1, -1)
b = EA(bias)

In [33]:
z = x2_dot_w2.add_bias(b)

In [34]:
z.values()

array([[15., 34.],
       [33., 79.]])