In [185]:
%load_ext autoreload
%autoreload 2
import numpy as np
from seal_wrapper import EA

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Vectors 

In [44]:
# model
w = [0.1, 0.05, 0.05, 0.2, 0.05, 0.3, 0.1, 0.025, 0.075, 0.05]
# data (sensitive)
x = [3.1, 4.159, 2.65, 3.5897, 9.3, 2.3, 8.46, 2.64, 3.383, 2.795]

In [45]:
np.dot(w, x)

3.828865

In [46]:
w = np.array(w).reshape(-1, 1)
x = np.array(x).reshape(1, -1)

In [47]:
encoded_w = EA(w)
encrypted_x = EA(x, True)

In [48]:
x_dot_w = encrypted_x.dot(encoded_w)
x_dot_w.values().flatten()[0]

3.8288649999999986

## Matrices 

In [49]:
w2 = np.array([[1, 2, 3], [4, 5, 6]])
x2 = np.array([[1, 2, 3], [4, 5, 6]])

In [50]:
np.dot(x2, w2.T)

array([[14, 32],
       [32, 77]])

In [51]:
encoded_w2 = EA(np.array(w2).T)
encrypted_x2 = EA(np.array(x2), True)

In [52]:
x2_dot_w2 = encrypted_x2.dot(encoded_w2)
x2_dot_w2.values()

array([[14., 32.],
       [32., 77.]])

In [53]:
bias = np.array([1, 2]).reshape(1, -1)
b = EA(bias)

In [54]:
z = x2_dot_w2 + b

In [55]:
z.values()

array([[15., 34.],
       [33., 79.]])

## Exponentiation

In [460]:
%autoreload 2

In [461]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [462]:
array = np.array([[-2, -1], [-0.5, 0], [0.5, 0.9], [2, 3]])

In [463]:
sigmoid(array)

array([[0.11920292, 0.26894142],
       [0.37754067, 0.5       ],
       [0.62245933, 0.7109495 ],
       [0.88079708, 0.95257413]])

In [464]:
array_enc = EA(array, True)

In [465]:
new = array_enc.activate_sigmoid()

0.5000000000000002
-0.49999999999999967
-0.9999999999999993

0.5000000000000002
-0.24999999999999986
-0.4999999999999997

0.5000000000000002
-0.12499999999999993
-0.24999999999999986

0.5000000000000002
0.0
0.0

0.5000000000000002
0.12499999999999993
0.24999999999999986

0.5000000000000002
0.22499999999999987
0.44999999999999973

0.5000000000000002
0.49999999999999967
0.9999999999999993

0.5000000000000002
0.7499999999999996
1.4999999999999991



In [466]:
new.values()

array([[-1.  , -0.5 ],
       [-0.25,  0.  ],
       [ 0.25,  0.45],
       [ 1.  ,  1.5 ]])

In [467]:
val1 = EA(np.array([0.6]).reshape(-1, 1), True)

In [468]:
val1.values()

array([[0.6]])

In [469]:
val1._pow3(val1.encrypted_values[0][0])

AttributeError: 'seal.Evaluator' object has no attribute 'multiplymany'